version: "3"
services:
  ubuntu:
    build: ./docker_files/ubuntu
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - ./:/home/usr/app
    command: /sbin/init
